### ISSUE TITLE
installation fails

### ISSUE THREAD

**Issue by avrahamm** [mike61988/magento2-dk#12]
Hello!
Windows 10 WSL
I followed instructions, ran several times
 C:\Users\avrahamm\Documents\magento\magento2-dk> docker-compose up -d
and cleaned by 
docker rmi -f imageId
each time, and tried again,
 but something fails
===========================
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

E: Failed to fetch http://deb.debian.org/debian/pool/main/n/net-snmp/snmp_5.7.3+dfsg-5_amd64.deb  Something wicked happened resolving 'deb.debian.org:http' (-5 - No address associated with hostname) [IP: 151.101.112.204 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
Fetched 4487 kB in 24s (185 kB/s)
ERROR: Service 'base' failed to build: The command '/bin/sh -c apt install -y   php7.2-bcmath php7.2-bz2 php7.2-cli php7.2-common
                                        php7.2-curl php7.2-dba php7.2-gd php7.2-gmp php7.2-imap
        php7.2-intl php7.2-ldap php7.2-mbstring                                         php7.2-mysql php7.2-odbc php7.2-pgsql php7.2-recode                                  php7.2-snmp php7.2-soap php7.2-sqlite php7.2-tidy                                       php7.2-xml php7.2-xmlrpc php7.2-xsl php7.2-zip' returned a non-zero code: 100

**Comment by avrahamm** [comment]
It succeeded after several trials.
Yet now next step:

C:\Users\avrahamm\Documents\magento\magento2-dk> docker exec -it m23 //bin/sh
# mv /var/www/html/magento2ce /var/www/html/shared/ && exit
mv: inter-device move failed: '/var/www/html/magento2ce' to '/var/www/html/shared/magento2ce'; unable to remove target: Directory not empty
#

**Comment by mike61988** [comment]
Hello,

Looks like you still need to move your Magento instance from '/var/www/html/magento2ce' to '/var/www/html/shared/magento2ce', since apache awaiting to see Magento in the this directory. You also may try to move it through the 'mc' application and then use 'F5' to copy and yes it's way much longer than on Unix systems, unfortunately. 

Let me know on what stage you are.

**Comment by avrahamm** [comment]
Is it possible to change apache configuration to avoid moving folder?

Anyway, after previous try I have /var/www/html/magento2ce moved partially
to /var/www/html/shared/magento2ce destination.

root@4d897396e525:/# ls /var/www/html/shared/magento2ce
CHANGELOG.md     auth.json.sample          nginx.conf.sample  setup
COPYING.txt      composer.json             node_modules       update
Gruntfile.js     composer.lock             package-lock.json  var
LICENSE.txt      grunt-config.json.sample  package.json       vendor
LICENSE_AFL.txt  index.php                 phpserver
SECURITY.md      lib                       pub
root@4d897396e525:/#

So I tried according to https://askubuntu.com/questions/269775/mv-directory-not-empty
root@4d897396e525:/# (cd /var/www/html/magento2ce && tar c .) | (cd /var/www/htm
l/shared/magento2ce && tar xf -)

It has been running for 4 hours, probably I will stop it in an hour. Yet opened
http://magento2u.loc:8080
Attached console output in console-fails.txt file
|
[console-fails.txt](https://github.com/mike61988/magento2-dk/files/4617541/console-fails.txt)

**Comment by wrodriguez81** [comment]
Hi, in my case the command docker-compose up -d worked fine, after several intent due slow internet.

know the command "winpty docker exec -it m23 //bin/sh" fails, it saids that winpty command is unknown. which tool i need to install to advance and get acces to my training evironment?

thanks in advance, Willians R.

**Comment by mike61988** [comment]
Hi avrahamm, yes it's possible to change the apache configuration, but in this case, the shared folder will be empty and you can edit the code only inside of the container but not outside.
As far as I can understand you did it a few times already and your shared folder is not empty (since docker remembers it from last time). You need to flush the shared folder and copy Magento to a shared folder again. You can try to use mv command or suggestion from my previous post.

**Comment by mike61988** [comment]
Hiwrodriguez81, 
Which OS do you use? Please see the following:
Open a terminal in that folder and run the following command:
For Unix/Mac/Windows with WSL
docker-compose up -d
Or, for Windows without WSL
docker-compose -f docker-compose_windows.yml up -d

**Comment by avrahamm** [comment]
Hi Mike, I will try to flush the shared folder and copy Magento to a shared folder again.
Thanks

**Comment by iphigenie** [comment]
I'm having a round and round here too. The command it creates as a link just won't work on my system - though the one created for kitematic will pop up and ask you to find bash, which helped figure out.

I think WSL has changed a lot, with a choice of distribution etc. and bash is no longer that easy to run explicitely. Or maybe I just havent finished configuring it properly. 

I suspect it is something that happens if you have newer powershell installed

What worked to start docker and install:

- opening a terminal and typing "C:\Program Files\Git\bin\bash.exe" -c " \"/c/Program Files/Docker Toolbox/start.sh\" \"%*\""  worked with one small error warning

- opening powershell and outright typing & 'C:\Program Files\Docker Toolbox\start.sh' also worked, it popped up asking me what to open it with, with git bash the top option and that opened screen where I could do the rest of the installation.

Once in this form of bash the "linux" commands work, not the "windows" commands 
@wrodriguez81 for me with WSL the "linux" command works: docker exec -ti m23 /bin/bash

also once installed and run once from these command lines it will appear in kitematic and "exec" from there opens the old powershell and it works.

The bit that is not working for me now is the mounting of the windows working directory "instances" into the machine under /var/www/html/shared

**Comment by mike61988** [comment]
hi @avrahamm, nice to hear that it works for you now. mutagen part is absolutely optional and only for the Unix OS at the moment.

**Comment by avrahamm** [comment]
Great! 
Thanks

**Comment by anjaligarg-web** [comment]
Hi,
I am using window10 without WSL. It shows me error at step 12
Step 12/12 : EXPOSE 80
 ---> Running in 488fce8ccc42
Removing intermediate container 488fce8ccc42
 ---> 3e77a4298ec2
Successfully built 3e77a4298ec2
Successfully tagged mike/m23_config:latest
WARNING: Image for service m23 was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.
Creating base ... done
Creating m23  ... error

ERROR: for m23  Cannot create container for service m23: status code not OK but 500: {"Message":"Unhandled exception: Filesharing has been cancelled","StackTrace":"   at Docker.ApiServices.Mounting.FileSharing.<DoShareAsync>d__6.MoveNext() in C:\\workspaces\\stable-2.3.x\\src\\github.com\\docker\\pinata\\win\\src\\Docker.ApiServices\\Mounting\\FileSharing.cs:line 0\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Docker.ApiServices.Mounting.FileSharing.<ShareAsync>d__4.MoveNext() in C:\\workspaces\\stable-2.3.x\\src\\github.com\\docker\\pinata\\win\\src\\Docker.ApiServices\\Mounting\\FileSharing.cs:line 47\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Docker.HttpApi.Controllers.FilesharingController.<ShareDirectory>d__2.MoveNext() in C:\\workspaces\\stable-2.3.x\\src\\github.com\\docker\\pinata\\win\\src\\Docker.HttpApi\\Controllers\\FilesharingController.cs:line 21\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__1`1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__5.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__15.MoveNext()"}

ERROR: for m23  Cannot create container for service m23: status code not OK but 500: {"Message":"Unhandled exception: Filesharing has been cancelled","StackTrace":"   at Docker.ApiServices.Mounting.FileSharing.<DoShareAsync>d__6.MoveNext() in C:\\workspaces\\stable-2.3.x\\src\\github.com\\docker\\pinata\\win\\src\\Docker.ApiServices\\Mounting\\FileSharing.cs:line 0\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Docker.ApiServices.Mounting.FileSharing.<ShareAsync>d__4.MoveNext() in C:\\workspaces\\stable-2.3.x\\src\\github.com\\docker\\pinata\\win\\src\\Docker.ApiServices\\Mounting\\FileSharing.cs:line 47\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Docker.HttpApi.Controllers.FilesharingController.<ShareDirectory>d__2.MoveNext() in C:\\workspaces\\stable-2.3.x\\src\\github.com\\docker\\pinata\\win\\src\\Docker.HttpApi\\Controllers\\FilesharingController.cs:line 21\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__1`1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__5.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__15.MoveNext()"}
ERROR: Encountered errors while bringing up the project.

**Comment by mike61988** [comment]
Hi @anjaligarg-web, it looks like you need to update the File Sharing configuration in your Docker for Windows. Go to Preferences -> Resources -> File Sharing and add all folders you need and then restart Docker for Windows.

**Comment by wrodriguez81** [comment]
> Hiwrodriguez81,
> Which OS do you use? Please see the following:
> Open a terminal in that folder and run the following command:
> For Unix/Mac/Windows with WSL
> docker-compose up -d
> Or, for Windows without WSL
> docker-compose -f docker-compose_windows.yml up -d

Hi, I was using w10, but i decided install a VM with ubuntu 20.04 and here all start working.
i am newbie with docker, and now i am confuse i how i interact with the app for register new modules and start the exercises of the Magento 2 Development course, any help will be apreciate

**Comment by mike61988** [comment]
Hi @wrodriguez81, 

Hope you are doing well!

Could you specify what exact questions you have at the moment, please?

Thank you,

**Comment by wrodriguez81** [comment]
Hi, basically I want to know how I interact with the magento application inside the container in order to do the course exercises, add new modules, modify topics, navigate folders with a file explorer, etc.

thanks on advance

**Comment by iphigenie** [comment]
Hi @wrodriguez81 - I know it is not what you want to hear but after I removed all the elements of old docker desktop and docker toolbox, and installed both the new WSL2 and the current Docker Desktop, things worked painlessly following the instructions here in the docs. https://github.com/mike61988/magento2-dk - and it then works like magic to pop up a dev site on your localhost

I think older versions were what caused my problem

WSL2 and docker desktop
https://docs.docker.com/docker-for-windows/install-windows-home/
(i found it easier to work with the WSL2)

**Comment by mike61988** [comment]
Thank you @iphigenie!
@wrodriguez81, did you have a chance to try @iphigenie recommendations? And also let me know please what way are you trying to follow right now (Windows with or without WSL, VM with ubuntu, etc), and please let me know if you ran the following command: "mv /var/www/html/magento2ce /var/www/html/shared/ && exit" and if you have Magento source code in your "instances" folder on the laptop at the moment?
Cheers,

**Comment by mike61988** [comment]
Hi @wrodriguez81,

Hope you are doing well!

Some information about docker you may find useful below:
docker images
https://docs.docker.com/engine/reference/commandline/images/

docker containers
https://docs.docker.com/engine/reference/commandline/container/

docker-compose
https://docs.docker.com/compose/

Hope it helps,

**Comment by willboudle** [comment]
So I have done this with WSL2 as iphigenie lays out. 
All the way up to moving code i.e
`"mv /var/www/html/magento2ce /var/www/html/shared/ && exit"`

The site loads, but the source code is not in my _instances_ folder

I installed mutagen but when I run that i get
`Extracting agent...
Error: create failed: unable to connect to beta: unable to connect to endpoint: unable to dial agent endpoint: unable to install agent: unable to get agent for platform: unable to locate agent bundle (search paths: [D:\Programs\mutagen])`

What can I try next?

**Comment by mike61988** [comment]
hi @willboudle,

Are you using mutagen_session.sh script to run mutagen session?
try to run this command instead, where default owner is root:
mutagen create --name=m23 --default-group-beta=www-data --default-owner-beta=root --sync-mode=two-way-resolved --default-file-mode=0664 --default-directory-mode=0755 --symlink-mode=posix-raw <PATH\TO\YOUR\magento\magento2-dev-dk\instances\> docker://root@m23/var/www/html/shared/

Another option is to use default docker volumes in docker-compose.yml file instead of mutagen.

**Comment by wrodriguez81** [comment]
> Thank you @iphigenie!
> @wrodriguez81, did you have a chance to try @iphigenie recommendations? And also let me know please what way are you trying to follow right now (Windows with or without WSL, VM with ubuntu, etc), and please let me know if you ran the following command: "mv /var/www/html/magento2ce /var/www/html/shared/ && exit" and if you have Magento source code in your "instances" folder on the laptop at the moment?
> Cheers,

Hi, i am using a VM with ubuntu 20.04, yes i ran the command you mentioned above, and no i don't have anything in the "instances" folder. is it there where a i have to put the code for new modules?

thanks in advance, sorry for the delayed reply, in the weekend i din't had internet conexion.

**Comment by mike61988** [comment]
Hi @wrodriguez81,

In that case, I can assume that you also used docker-compose -d command then, if so you then you have to use mutagen or default docker volumes in the docker-compose.yml file.
Mutagen:
https://github.com/mike61988/magento2-dk#using-mutagen
or
docker volumes example you may find in the docker-compose.yml:
file, then re-run docker-compose.

**Comment by wrodriguez81** [comment]
> Hi @wrodriguez81,
> 
> In that case, I can assume that you also used docker-compose -d command then, if so you then you have to use mutagen or default docker volumes in the docker-compose.yml file.
> Mutagen:
> https://github.com/mike61988/magento2-dk#using-mutagen
> or
> docker volumes example you may find in the docker-compose.yml:
> file, then re-run docker-compose.

I used docker-compose up -d

**Comment by mike61988** [comment]
Hi, @wrodriguez81 then you have to use the default docker volumes as I mentioned in the previous post. You need to use one of the real-time file synchronization tools in case if you want to edit code directly on your laptop.

Hope it helps!

**Comment by iphigenie** [comment]
I didnt use mutagen either - on windows it's no longer needed with the new VS Code integration

I installed vs code and the two extentions "Remote WSL" and "Remote Containers"

I type `code .`  from WSL in the directory that contains the docker-compose - this starts the editor within WSL and I can edit things there because I mapped folders. 

If you didnt map folders, from there you can open the folder in the container and work direct there.

**Comment by mike61988** [comment]
Hi @iphigenie, great, thank you!

Those who interested please try it if you still don't!

**Comment by iphigenie** [comment]
If it helps, I did take notes - not totally complete but should be enough to get there on windows

**SETUP ON WINDOWS 10**

You must be on the newest windows version - 2004 or later - it's called "May 10" but not widely rolled out yet, though insider slow ring is on it. May 28th supposedly (posted the 27th)

WSL2 install [https://docs.microsoft.com/en-us/windows/wsl/install-win10#update-to-wsl-2](https://docs.microsoft.com/en-us/windows/wsl/install-win10#update-to-wsl-2), 

linux kernel update [https://aka.ms/wsl2kernel](https://aka.ms/wsl2kernel)  - if you already had WSL1 you might have to uninstall and reinstall it (it's explained in the doc)

Go to windows store, search "WSL" to list all apps. 

Add Debian  - suse and alpine didnt seem to be fully integrated for this yet. 

In windows console change default to wsl2 and debian distribution to wsl 2

```
wsl --set-default-version 2
wsl --set-version debian 2
```
if you see usage information you are on wsl1 still

add git, nodejs to your distribution

Install latest Docker desktop updated [https://www.docker.com/products/docker-desktop](https://www.docker.com/products/docker-desktop) choose WSL2 for containers  in its settings activate distribution

now you will have wsl integrated with debian and you can see the windows docker from the linux environment

if not already have it, install VS Code  [https://code.visualstudio.com](https://code.visualstudio.com)
add extensions docker, remote - containers, remote - wsl to code - I also recommend adding a php  json and less extension, maybe graphql

**Working with Code and  WSL** 

You can now start a debian session from start menu (distribution entry), or from command line as `debian` or `wsl`

within that you can navigate both your internal linux filesystem and the windows filesystem 
check: `code .` starts vs code and the `docker ps` command should work

note: You need to reactivate VS Code extension within WSL

instead of starting VS Code from WSL you can also start wsl from VS Code via *Remote-WSL" (in commands or clicking the location/remote corner bottom left)  and then starting a terminal within code.

The Remote-Containers and the Docker extensions offer different ways 

Remote-Containers is about working in them, Docker more about managing or creating your own containers. Both can start a container with VS editor and terminal attached and working for live editing sessions. Worth reading up their description and 
https://code.visualstudio.com/docs/remote/containers
https://code.visualstudio.com/docs/containers/overview

**Building containers:**

Running from WSL shell or from normal windows console is a touch different but in both cases you start create a working directory, clone the repository, edit the file, create an instances folder and start the build from within the instance folder 

Information is things are faster if you work within WSL rather than windows folders

create a project directory - eg for the magento tutorial code I created working/magento2-dk-on-linux/
in this folder clone or download https://github.com/mike61988/magento2-dk/
git clone https://github.com/mike61988/magento2-dk.git

now open this folder in code and open terminal within code, for speed

Copy debian_config/composer/auth.json.sample to debian_config/composer/auth.json and enter your public (username) and private (password) access keys.
create a folder called instances within that directory.

modify file mapping in `docker-compose.yml` if needed
I just have:

```
    volumes:
      - ./instances:/var/www/html/shared
```

change to instances directory
`docker-compose up -d`

This can be done in the WSL command prompt also in VS Code Terminal if started from WSL. It can also be done via the VS Code extension tools but I tend to have to redo things a few times so command line is quicker (if you mess up docker-compose down -v --rmi local cleans most)

Look at the Docker Dashboard or the Docker section in VS Code as now things can be started/stopped from there or console started

first time run this in the console: mv /var/www/html/magento2ce /var/www/html/shared/ && exit
otherwise the website will show an error.

THIS WILL TAKE AN AGE esp if you are on windows folder. 

**Ongoing development:**

start code from the WSL command line as code . then you can start the container - for me opening the folder in VS Code then the command "Remote-Containers reopen in container" gives me an editor and console on the container and the website working on the http://magento2u.loc:8080 subdomain.

Since I mapped a WSL folder I dont need to open in the container, just make sure it is running - this approache also allows me to use a workspace with other folders that aren't in the container (for copy paste). 

This might be possible with "open in container" too - there were workspace options and options to add other folders to workspace. I just havent tested far yet.


Note: easy to get mixed up between the WSL terminal and the container internal terminal especially if you have a VS Code with the WSl version and a VS Code with the Container version both open.


Last thing: Windows Terminal colors 
https://devblogs.microsoft.com/commandline/new-experimental-console-features/

honestly that dark blue on black is a horror.

**Comment by mike61988** [comment]
@iphigenie thank you a lot!!!

Those who interested please try it if you still don't!

**Comment by mike61988** [comment]
closed due to inactivity
